### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by wangtao090620** [bytedance/pangle-sdk-demo#4]
Caused by java.lang.ClassNotFoundException
Didn't find class "com.bytedance.sdk.openadsdk.multipro.TTMultiProvider" on path: DexPathList[[zip file "/data/app/-drHje0PxbBjz0EvEj3OdYQ==/base.apk", zip file 
"/data/app/-drHje0PxbBjz0EvEj3OdYQ==/split_config.arm64_v8a.apk", zip file "
/data/app/-drHje0PxbBjz0EvEj3OdYQ==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/-drHje0PxbBjz0EvEj3OdYQ==/lib/arm64, 
/data/app/-drHje0PxbBjz0EvEj3OdYQ==/base.apk!/lib/arm64-v8a, 
/data/app/com.novel.fiction.read.story.book-drHje0PxbBjz0EvEj3OdYQ==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/-drHje0PxbBjz0EvEj3OdYQ==/split_config.xhdpi.apk!/lib/arm64-v8a, /system/lib64]]，

我们在Firebase上看上报了这个错误，但是我们已经配置了，不知道是什么问题

**Comment by aabolfazl** [comment]
I have this issue too.

` java.lang.RuntimeException: Unable to get provider com.bytedance.sdk.openadsdk.multipro.TTMultiProvider: java.lang.ClassNotFoundException: Didn't find class "com.bytedance.sdk.openadsdk.multipro.TTMultiProvider" on path: DexPathList[[zip file "/data/app/~~69gqGIgUpyuBo4MaTT56Tw==/apppakagename-ZuLMoXCejAsszNyLfMyOvg==/base.apk"],nativeLibraryDirectories=[/data/app/~~69gqGIgUpyuBo4MaTT56Tw==/apppakagename-ZuLMoXCejAsszNyLfMyOvg==/lib/arm64, /data/app/~~69gqGIgUpyuBo4MaTT56Tw==/apppakagename-ZuLMoXCejAsszNyLfMyOvg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by tunzhao** [comment]
请问你们是怎么解决的
